### ISSUE TITLE
vkq music won't work with cyrillic

### ISSUE THREAD

**Issue by kosc** [grwlf/vkhs#1]
When I input this:
 vkq music -a <access_token> -l -q "Some Music Group" 1 - it returns list of songs for "Some Music Group", but when I input this:
 vkq music -a <access_token> -l -q "Какая-то группа" 1 - I'll got one of that:
- One wrong song
- List of wrong songs
- Error because of timeout

**Comment by sergei-mironov** [comment]
New version is available, could you please re-check the issue?

**Comment by sergei-mironov** [comment]
Cyrillic should work now. No more music in VK, unfortunately.
